import { test, expect } from '@playwright/test'
async function login(page) {
  await page.goto('/')
  await page.getByLabel('Email', { exact: true }).fill('learner@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('demo123')
  await page.getByRole('button', { name: 'Đăng nhập' }).click()
  await page.getByRole('button', { name: 'Bắt đầu Quiz' }).click()
  await expect(page.getByText('Câu 1/5', { exact: true })).toBeVisible()
}
async function answer(page, index) {
  await page.getByRole('group', { name: 'Các đáp án' }).getByRole('button').nth(index).click()
  await page.locator('.question-footer button').click()
}
async function wrongQuiz(page) { await answer(page, 1); await page.getByRole('button', { name: 'Xem giải thích' }).click() }
async function failPrerequisites(page) {
  await wrongQuiz(page)
  await page.getByRole('button', { name: 'Tiếp tục ôn', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Kiểm tra nhanh — Vòng 1/2' })).toBeVisible()
  await answer(page, 1)
  await page.getByRole('button', { name: 'Tiếp tục vòng 2' }).click()
  await expect(page.getByRole('heading', { name: 'Kiểm tra nhanh — Vòng 2/2' })).toBeVisible()
  await answer(page, 1)
  await page.getByRole('button', { name: 'Chọn cách ôn tập' }).click()
}
test('A: correct → next; navigation preserves answer selection', async ({ page }) => {
  await login(page); await answer(page, 0)
  await expect(page.getByText('Chính xác!', { exact: true })).toBeVisible()
  await expect(page.locator('.answer.correct')).toHaveCount(1)
  await page.getByRole('button', { name: 'Câu tiếp theo' }).click()
  await expect(page.getByText('Câu 2/5', { exact: true })).toBeVisible()
  await page.locator('.answer').nth(2).click()
  await page.getByRole('navigation').getByRole('button', { name: 'Trang chủ' }).click()
  await page.getByRole('button', { name: 'Tiếp tục phiên học' }).click()
  await expect(page.getByText('Câu 2/5', { exact: true })).toBeVisible()
  await expect(page.locator('.answer.selected')).toHaveCount(1)
})
test('B: wrong → explanation → similar correct → quiz', async ({ page }) => {
  await login(page); await wrongQuiz(page)
  await expect(page.locator('.answer.incorrect')).toHaveCount(1)
  await expect(page.locator('.answer.correct')).toHaveCount(1)
  await page.getByRole('button', { name: 'Thử một ví dụ khác' }).click()
  await answer(page, 1)
  await expect(page.getByText('Có vẻ bạn đã hiểu concept nhưng đã nhầm hoặc áp dụng sai ở câu trước.')).toBeVisible()
  await page.getByRole('button', { name: 'Quay lại Quiz' }).click()
  await expect(page.getByText('Câu 2/5', { exact: true })).toBeVisible()
})
test('C: similar wrong → prerequisite round 1', async ({ page }) => {
  await login(page); await wrongQuiz(page)
  await page.getByRole('button', { name: 'Thử một ví dụ khác' }).click()
  await answer(page, 0)
  await page.getByRole('button', { name: 'Kiểm tra kiến thức nền' }).click()
  await expect(page.getByRole('heading', { name: 'Kiểm tra nhanh — Vòng 1/2' })).toBeVisible()
})
test('D: failed rounds → summary → original question retry', async ({ page }) => {
  await login(page); await failPrerequisites(page)
  await page.getByRole('button', { name: 'Tổng hợp kiến thức' }).click()
  await expect(page.locator('.knowledge-card')).toHaveCount(3)
  await page.getByRole('button', { name: 'Thử lại câu ban đầu' }).click()
  await expect(page.getByRole('heading', { name: 'Một mô hình ngôn ngữ lớn tạo ra câu trả lời bằng cách nào?' })).toBeVisible()
  await answer(page, 0)
  await page.getByRole('button', { name: 'Quay lại Quiz' }).click()
  await expect(page.getByText('Câu 2/5', { exact: true })).toBeVisible()
})
test('E: deep review incorrect → retry resets question', async ({ page }) => {
  await login(page); await failPrerequisites(page)
  await page.getByRole('button', { name: 'Ôn tập chuyên sâu' }).click()
  await answer(page, 1)
  await expect(page.getByText('Bạn đã trả lời sai kiến thức cơ bản và cần ôn tập lại phần Dữ liệu văn bản.')).toBeVisible()
  await page.getByRole('button', { name: 'Ôn lại phần này' }).click()
  await expect(page.locator('.question-footer button')).toBeDisabled()
  await expect(page.locator('.mini-lesson')).toBeVisible()
})
for (const finish of [false, true]) test(`F: deep review correct → ${finish ? 'finish and history' : 'return quiz'}`, async ({ page }) => {
  await login(page); await failPrerequisites(page)
  await page.getByRole('button', { name: 'Ôn tập chuyên sâu' }).click()
  await answer(page, 0)
  await expect(page.getByText('Bạn đã nắm được phần kiến thức cơ bản này.')).toBeVisible()
  if (finish) {
    await page.getByRole('button', { name: 'Kết thúc phiên học', exact: true }).first().click()
    await expect(page.getByRole('heading', { name: 'Phiên học đã kết thúc' })).toBeVisible()
    await page.getByRole('button', { name: 'Về trang chủ' }).click()
    await page.getByRole('navigation').getByRole('button', { name: 'Tiến độ', exact: true }).click()
    await expect(page.getByText('Đã kết thúc sớm')).toBeVisible()
    await expect(page.getByText('0/1 câu đã trả lời đúng · 1/5 câu đã làm')).toBeVisible()
  } else {
    await page.getByRole('button', { name: 'Quay lại Quiz ban đầu' }).click()
    await expect(page.getByText('Câu 2/5', { exact: true })).toBeVisible()
  }
})
test('Prerequisite correct → recheck incorrect → review without third round', async ({ page }) => {
  await login(page); await wrongQuiz(page)
  await page.getByRole('button', { name: 'Tiếp tục ôn', exact: true }).click()
  await answer(page, 0)
  await page.getByRole('button', { name: 'Kiểm tra lại concept' }).click()
  await answer(page, 0)
  await page.getByRole('button', { name: 'Tổng hợp kiến thức' }).click()
  await expect(page.locator('.knowledge-card')).toHaveCount(3)
  await expect(page.getByText('Vòng 3', { exact: false })).toHaveCount(0)
})
test('Complete quiz counts initial answers once', async ({ page }) => {
  await login(page)
  for (const [i, choice] of [0, 1, 2, 1, 3].entries()) {
    await answer(page, choice)
    await page.getByRole('button', { name: i === 4 ? 'Xem kết quả' : 'Câu tiếp theo' }).click()
  }
  await expect(page.getByRole('heading', { name: 'Bạn đã hoàn thành quiz!' })).toBeVisible()
  await expect(page.locator('.completion-stats strong').first()).toHaveText('5/5')
})
test('Registration validation, logout and mobile layout', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/')
  await page.getByRole('button', { name: 'Đăng ký', exact: true }).click()
  await page.getByLabel('Họ và tên').fill('Minh Anh')
  await page.getByLabel('Email', { exact: true }).fill('minh@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('demo123')
  await page.getByLabel('Xác nhận mật khẩu').fill('wrong123')
  await page.getByRole('button', { name: 'Tạo tài khoản' }).click()
  await expect(page.getByRole('alert')).toHaveText('Mật khẩu xác nhận chưa khớp.')
  await page.getByLabel('Xác nhận mật khẩu').fill('demo123')
  await page.getByRole('button', { name: 'Tạo tài khoản' }).click()
  await expect(page.getByRole('heading', { name: 'Bạn muốn ôn tập nội dung nào?' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/mobile-home.png', fullPage: true })
  await page.getByRole('button', { name: 'Bắt đầu Quiz' }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('.profile summary').click()
  await page.getByRole('button', { name: 'Đăng xuất' }).click()
  await expect(page.getByRole('heading', { name: 'Chào mừng bạn trở lại' })).toBeVisible()
})
test('Desktop visual snapshots', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.goto('/')
  await page.screenshot({ path: 'test-results/desktop-login.png', fullPage: true })
  await page.getByLabel('Email', { exact: true }).fill('minhanh@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('demo123')
  await page.getByRole('button', { name: 'Đăng nhập' }).click()
  await page.screenshot({ path: 'test-results/desktop-home.png', fullPage: true })
})
